spring:
  application:
    name: mongox


  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://shashi123:system123@shashitech.oykwn9f.mongodb.net/}
      database: shashitechltd

server:
  port: ${PORT:8081}
  address: 0.0.0.0

cloud:
  aws:
    s3:
      access-key: ${AWS_ACCESS_KEY_ID:dummy}
      secret-key: ${AWS_SECRET_ACCESS_KEY:dummy}
      region: eu-north-1


    region:
      static: eu-north-1   # Change to the actual region of your S3 bucket
    stack:
      auto: false

logging:
  level:
    org.springframework.security: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

jwt:
  secret: "this-is-a-very-strong-random-secret-key-32chars-min!"
  ttlSeconds: 2592000  # 30 days
