server:
  port: ${REST_PORT:8080}   # default 8080, can override with ENV
  address: 0.0.0.0

grpc:
  server:
    port: ${GRPC_PORT:9090} # default 9090, can override with ENV


spring:
  application:
    name: mongox


  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://shashi123:system123@shashitech.oykwn9f.mongodb.net/}
      database: shashitechltd

cloud:
  aws:
    s3:
      access-key: ${AWS_ACCESS_KEY_ID:dummy}
      secret-key: ${AWS_SECRET_ACCESS_KEY:dummy}
      region: eu-north-1


    region:
      static: eu-north-1   # Change to the actual region of your S3 bucket
    stack:
      auto: false
