spring:
  application:
    name: mongox


  data:
    mongodb:
      uri: mongodb+srv://username:password@cluster.mongodb.net/dbname?retryWrites=true&w=majority
      database: ${MONGODB_DB:shashitechltd}

server:
  port: ${PORT:8080}
  address: 0.0.0.0

cloud:
  aws:
    s3:
      access-key: ${AWS_ACCESS_KEY_ID:dummy}
      secret-key: ${AWS_SECRET_ACCESS_KEY:dummy}
      region: eu-north-1


    region:
      static: eu-north-1   # Change to the actual region of your S3 bucket
    stack:
      auto: false
