name: Build and Push Docker Image

on:
  push:
    branches:
      - master   # runs when you push to main branch
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up JDK (for Maven build)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Build JAR with Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # 4. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Build and push image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: jshashank388/mongox:latest
          
      # 6. Deploy to Railway using CLI Docker image
      - name: Deploy to Railway
        uses: docker://ghcr.io/railwayapp/cli:latest
        with:
          args: up --service=mongox -- --image jshashank388/mongox:latest
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

