name: CI/CD Railway Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Build & Push Docker image to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mongox:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/mongox:latest

      # Deploy to Railway
      - name: Deploy to Railway
        uses: railwayapp/railway-action@v1
        with:
          railwayToken: ${{ secrets.RAILWAY_TOKEN }}
          service: mongox
          dockerImage: ${{ secrets.DOCKER_USERNAME }}/mongox:latest
          # If your Railway service uses Docker Hub image:
          # dockerImage: ${{ secrets.DOCKER_USERNAME }}/mongox:latest
